# 设置只监听哪个分支
branches:
  only:
  - master
  
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "fydy"
- git config --global user.email "edu@yuns.me"

after_success:
- cd ./*
- git init
- git add --all .
- git commit -m "Travis CI Auto Builder"
- git checkout --orphan coding-pages
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的
- git push --quiet --force https://$jekll@git.coding.net/deweke/zblog.git
  coding-pages
