language: ruby
rvm:
  - 2.4.1
  
# 设置只监听哪个分支
branches:
  only:
  - master
  
script:
  - gem install bundler jekyll
  
after_success:
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git checkout --orphan coding-pages
  - git add --all .
  - git commit -m "Travis CI Auto Builder"
  # Coding Pages
  - git push --force --quiet "https://deweke:${CO_TOKENT}@${CO_REF}" coding-pages:coding-pages

env:
 global:
   # Coding Pages
   - CO_REF: git.coding.net/deweke/zblog.git
